name: Build Switch Only

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build (nintendoswitch, aarch64, vanilla-nintendoswitch-image.zip)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: image-nintendoswitch
          platforms: linux/arm64
          outputs: type=local,dest=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vanilla-nintendoswitch-image
          path: dist/*
